GO
use DayHocTrucTuyen
GO

ALTER TABLE LopHoc
DROP COLUMN Mat_Khau;


GO
INSERT [dbo].[LopHoc] ([Ma_Lop], [Ma_ND], [Ngay_Tao], [Ten_Lop], [Bi_Danh], [Gia_Tien], [Mo_Ta], [Trang_Thai], [Img_Bia]) VALUES (N'ajg-atv-ims', N'U000001', CAST(N'2022-04-14T23:45:33.100' AS DateTime), N'Test chương trình', N'ajg-atv-ims', 0, N'Lớp học tạo ra để kiểm tra các tính năng', 1, N'ajg-atv-ims-101.png')
INSERT [dbo].[LopHoc] ([Ma_Lop], [Ma_ND], [Ngay_Tao], [Ten_Lop], [Bi_Danh], [Gia_Tien], [Mo_Ta], [Trang_Thai], [Img_Bia]) VALUES (N'atk-spu-upa', N'U000002', CAST(N'2022-12-11T11:38:29.337' AS DateTime), N'AI không khó', N'atk-spu-upa', 0, N'Đào tạo kiến thức AI căn bản, buils 1 con AI giúp bán hàng nhanh.', 1, NULL)
INSERT [dbo].[LopHoc] ([Ma_Lop], [Ma_ND], [Ngay_Tao], [Ten_Lop], [Bi_Danh], [Gia_Tien], [Mo_Ta], [Trang_Thai], [Img_Bia]) VALUES (N'eep-phg-aop', N'U000004', CAST(N'2022-12-11T11:48:36.903' AS DateTime), N'AI thật dễ? Tại sao không?', N'eep-phg-aop', 0, NULL, 1, NULL)
INSERT [dbo].[LopHoc] ([Ma_Lop], [Ma_ND], [Ngay_Tao], [Ten_Lop], [Bi_Danh], [Gia_Tien], [Mo_Ta], [Trang_Thai], [Img_Bia]) VALUES (N'ets-mcd-epp', N'U000002', CAST(N'2022-12-11T11:42:57.443' AS DateTime), N'AI và bạn', N'ets-mcd-epp', 0, N'Hướng dẫn tạo AI trò chuyện với Python', 1, NULL)
INSERT [dbo].[LopHoc] ([Ma_Lop], [Ma_ND], [Ngay_Tao], [Ten_Lop], [Bi_Danh], [Gia_Tien], [Mo_Ta], [Trang_Thai], [Img_Bia]) VALUES (N'fpv-gnj-laj', N'U000006', CAST(N'2022-04-20T09:27:27.520' AS DateTime), N'Lập Trình Web Nâng Cao', N'laptrinhwebnangcao', 0, N'Dạy kỹ thuật nâng cao cho những bạn yêu thích mảng lập trình web.', 1, N'fpv-gnj-laj-883.png')
INSERT [dbo].[LopHoc] ([Ma_Lop], [Ma_ND], [Ngay_Tao], [Ten_Lop], [Bi_Danh], [Gia_Tien], [Mo_Ta], [Trang_Thai], [Img_Bia]) VALUES (N'hjh-dea-iuu', N'U000004', CAST(N'2022-12-11T11:46:34.863' AS DateTime), N'Nói không với ngoại ngữ?', N'hjh-dea-iuu', 0, N'Bạn đang sợ Tiếng Anh? Bạn không biết học ngoại ngữ như thế nào là đúng? Hãy để tôi giúp bạn.', 1, NULL)
INSERT [dbo].[LopHoc] ([Ma_Lop], [Ma_ND], [Ngay_Tao], [Ten_Lop], [Bi_Danh], [Gia_Tien], [Mo_Ta], [Trang_Thai], [Img_Bia]) VALUES (N'hru-bpv-nul', N'U000006', CAST(N'2022-12-11T11:07:13.437' AS DateTime), N'Lớp Toán cô Nguyệt', N'hru-bpv-nul', 20000, N'Dạy toán cho học sinh lớp 12', 1, NULL)
INSERT [dbo].[LopHoc] ([Ma_Lop], [Ma_ND], [Ngay_Tao], [Ten_Lop], [Bi_Danh], [Gia_Tien], [Mo_Ta], [Trang_Thai], [Img_Bia]) VALUES (N'ifd-tcm-anp', N'U000001', CAST(N'2022-12-11T11:36:18.787' AS DateTime), N'Tiếng Anh căn bản', N'ifd-tcm-anp', 0, N'Đào tạo tiếng anh cho các bạn mất gốc, đảm bảo chất lượng IELS trên 6.5', 1, NULL)
INSERT [dbo].[LopHoc] ([Ma_Lop], [Ma_ND], [Ngay_Tao], [Ten_Lop], [Bi_Danh], [Gia_Tien], [Mo_Ta], [Trang_Thai], [Img_Bia]) VALUES (N'jki-mfu-mvc', N'U000004', CAST(N'2022-12-11T11:47:17.310' AS DateTime), N'Lập trình PHP', N'jki-mfu-mvc', 0, N'Hướng dẫn lập trình web với PHP', 1, NULL)
INSERT [dbo].[LopHoc] ([Ma_Lop], [Ma_ND], [Ngay_Tao], [Ten_Lop], [Bi_Danh], [Gia_Tien], [Mo_Ta], [Trang_Thai], [Img_Bia]) VALUES (N'kfl-qpg-jgq', N'U000001', CAST(N'2022-12-11T11:34:02.123' AS DateTime), N'Hóa - Sinh', N'kfl-qpg-jgq', 0, N'Dạy hóa học và sinh học cho các bạn lớp 12 mất căn bản', 1, NULL)
INSERT [dbo].[LopHoc] ([Ma_Lop], [Ma_ND], [Ngay_Tao], [Ten_Lop], [Bi_Danh], [Gia_Tien], [Mo_Ta], [Trang_Thai], [Img_Bia]) VALUES (N'kge-gbn-vdl', N'U000006', CAST(N'2022-12-11T09:51:05.090' AS DateTime), N'Lập Trình .Net', N'kge-gbn-vdl', 0, N'Lớp dạy lập trình .net căn bản', 1, NULL)
INSERT [dbo].[LopHoc] ([Ma_Lop], [Ma_ND], [Ngay_Tao], [Ten_Lop], [Bi_Danh], [Gia_Tien], [Mo_Ta], [Trang_Thai], [Img_Bia]) VALUES (N'mfo-chj-hta', N'U000006', CAST(N'2022-04-20T09:24:44.187' AS DateTime), N'Lập Trình Web', N'mfo-chj-hta', 60000, N'Dành cho những ai có yêu thích lập trình web', 1, NULL)
INSERT [dbo].[LopHoc] ([Ma_Lop], [Ma_ND], [Ngay_Tao], [Ten_Lop], [Bi_Danh], [Gia_Tien], [Mo_Ta], [Trang_Thai], [Img_Bia]) VALUES (N'njt-grc-eis', N'U000004', CAST(N'2022-12-11T11:50:19.897' AS DateTime), N'PHP căn bản', N'njt-grc-eis', 0, NULL, 1, NULL)
INSERT [dbo].[LopHoc] ([Ma_Lop], [Ma_ND], [Ngay_Tao], [Ten_Lop], [Bi_Danh], [Gia_Tien], [Mo_Ta], [Trang_Thai], [Img_Bia]) VALUES (N'nqa-sot-ofo', N'U000004', CAST(N'2022-12-11T11:50:03.683' AS DateTime), N'Phython căn bản', N'nqa-sot-ofo', 0, NULL, 1, NULL)
INSERT [dbo].[LopHoc] ([Ma_Lop], [Ma_ND], [Ngay_Tao], [Ten_Lop], [Bi_Danh], [Gia_Tien], [Mo_Ta], [Trang_Thai], [Img_Bia]) VALUES (N'pqr-uvl-hmu', N'U000006', CAST(N'2022-04-20T09:25:37.443' AS DateTime), N'Java Cho Người Mới', N'pqr-uvl-hmu', 150000, N'Dạy java căn bản cho người mới và các bạn mất kiến thức căn bản', 1, NULL)
INSERT [dbo].[LopHoc] ([Ma_Lop], [Ma_ND], [Ngay_Tao], [Ten_Lop], [Bi_Danh], [Gia_Tien], [Mo_Ta], [Trang_Thai], [Img_Bia]) VALUES (N'rcm-lqv-mhi', N'U000002', CAST(N'2022-12-11T11:40:16.463' AS DateTime), N'Hướng đối tượng OOP', N'rcm-lqv-mhi', 0, N'Thế nào là lập trình hướng đối tượng? Ứng dụng của nó là gì?', 1, NULL)
INSERT [dbo].[LopHoc] ([Ma_Lop], [Ma_ND], [Ngay_Tao], [Ten_Lop], [Bi_Danh], [Gia_Tien], [Mo_Ta], [Trang_Thai], [Img_Bia]) VALUES (N'svp-aku-qgd', N'U000004', CAST(N'2022-12-11T11:48:05.697' AS DateTime), N'Web với C#', N'svp-aku-qgd', 0, NULL, 1, NULL)
INSERT [dbo].[LopHoc] ([Ma_Lop], [Ma_ND], [Ngay_Tao], [Ten_Lop], [Bi_Danh], [Gia_Tien], [Mo_Ta], [Trang_Thai], [Img_Bia]) VALUES (N'tep-bje-sma', N'U000001', CAST(N'2022-03-27T17:56:28.623' AS DateTime), N'Lớp học đầu tiên', N'tep-bje-sma', 350000, NULL, 1, N'tep-bje-sma-622.png')
INSERT [dbo].[LopHoc] ([Ma_Lop], [Ma_ND], [Ngay_Tao], [Ten_Lop], [Bi_Danh], [Gia_Tien], [Mo_Ta], [Trang_Thai], [Img_Bia]) VALUES (N'tfs-cle-cjf', N'U000006', CAST(N'2022-12-11T11:16:27.110' AS DateTime), N'Toán - Lý', N'tfs-cle-cjf', 20000, N'Lớp dạy toán lý ôn tập cho các bạn thi đại học', 1, NULL)
INSERT [dbo].[LopHoc] ([Ma_Lop], [Ma_ND], [Ngay_Tao], [Ten_Lop], [Bi_Danh], [Gia_Tien], [Mo_Ta], [Trang_Thai], [Img_Bia]) VALUES (N'tig-ptk-sok', N'U000001', CAST(N'2022-12-11T11:35:07.140' AS DateTime), N'Ngữ văn 12', N'tig-ptk-sok', 0, N'Sự giàu đẹp của thơ ca, văn học Việt Nam trong chương trình giảng dạy lớp 12.', 1, NULL)
INSERT [dbo].[LopHoc] ([Ma_Lop], [Ma_ND], [Ngay_Tao], [Ten_Lop], [Bi_Danh], [Gia_Tien], [Mo_Ta], [Trang_Thai], [Img_Bia]) VALUES (N'tsm-gat-pas', N'U000002', CAST(N'2022-12-11T11:39:38.633' AS DateTime), N'Quy tắc lập trình', N'tsm-gat-pas', 0, N'Dạy cơ bản về các quy tắc lập trình căn bản', 1, NULL)
INSERT [dbo].[LopHoc] ([Ma_Lop], [Ma_ND], [Ngay_Tao], [Ten_Lop], [Bi_Danh], [Gia_Tien], [Mo_Ta], [Trang_Thai], [Img_Bia]) VALUES (N'unu-lqn-hph', N'U000002', CAST(N'2022-12-11T11:42:06.890' AS DateTime), N'Lý thuyết đồ thị', N'unu-lqn-hph', 0, NULL, 1, NULL)
GO